package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>这是一种新的支付方式, 为用户提供一种新的支付服务. 它应该是怎样一种服务呢?</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"ext/resources/css/ext-all.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"ext/adapter/ext/ext-base.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"ext/ext-core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"ext/ext-all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/budget/budgetItem_add.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/portal.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont: 12px/1.5 tahoma,arial,Hiragino Sans GB,宋体;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    /*\r\n");
      out.write("    background: #7F99BE url(images/top1.jpg) repeat-x center;\r\n");
      out.write("    */\r\n");
      out.write("    /*\r\n");
      out.write("    background: #7F99BE url(images/top_title2.jpg) no-repeat right center;\r\n");
      out.write("    */\r\n");
      out.write("    background: #7F99BE url(images/top_title_bg.jpg) repeat right center;\r\n");
      out.write("}\r\n");
      out.write("#header2 {\r\n");
      out.write("    /*\r\n");
      out.write("    background: #7F99BE url(images/top1.jpg) repeat-x center;\r\n");
      out.write("    */\r\n");
      out.write("    background: url(images/top_title2.jpg) no-repeat right bottom;\r\n");
      out.write("}\r\n");
      out.write("#header h1 {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#topMenu\r\n");
      out.write("{\r\n");
      out.write("float:left;\r\n");
      out.write("width:100%;\r\n");
      out.write("padding:0;\r\n");
      out.write("margin:0;\r\n");
      out.write("list-style-type:none;\r\n");
      out.write("}\r\n");
      out.write("#topMenu li a\r\n");
      out.write("{\r\n");
      out.write("float:left;\r\n");
      out.write("/*width:7em;*/\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("color:white;\r\n");
      out.write("/*background-color:purple;*/\r\n");
      out.write("padding: 0px 4px;\r\n");
      out.write("border-right:0px solid white;\r\n");
      out.write("}\r\n");
      out.write("/*#topMenu li a:hover {background-color:#ff3300}*/\r\n");
      out.write("#topMenu li {display:inline;}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("function calljojoo() {\r\n");
      out.write("    window.open('http://www.google.cn/','calljojoo','top=0,left=0,width=200,height=600,status=no,resizable=no,scrollbars=no, toolbar=no, menubar=no, location=no');\r\n");
      out.write("}\r\n");
      out.write("function login() {\r\n");
      out.write("    window.open('login.jsp', 'login', 'width=420, height=500');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showLoginForm() {\r\n");
      out.write("\tvar e = document.getElementById('login_form');\r\n");
      out.write("\r\n");
      out.write("\tvar left = (document.body.clientWidth - e.clientWidth) / 2;\r\n");
      out.write("\tvar top = (document.body.clientHeight - e.clientHeight) / 2;\r\n");
      out.write("\tleft += document.body.scrollLeft;\r\n");
      out.write("\ttop += document.body.scrollTop;\r\n");
      out.write("\te.style.left = left;\r\n");
      out.write("\te.style.top = top;\r\n");
      out.write("\t\r\n");
      out.write("\tvar display = e.style.display == 'block';\r\n");
      out.write("\tif (display == true) {\r\n");
      out.write("\t\te.style.display = 'none';\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\te.style.display = 'block';\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function calljojoo2() {\r\n");
      out.write("\twindow.open('http://www.google.cn/','_blnak','top=100,left=100,width=200,height=600,status=no,resizable=no,scrollbars=no, toolbar=no, menubar=no, location=no');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function register3() {\r\n");
      out.write("\twindow.open('register.jsp','_blnak','top=100,left=100,width=800,height=600,status=no,resizable=no,scrollbars=yes, toolbar=no, menubar=no, location=no, titlebar=no');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function calljojoo4() {\r\n");
      out.write("\tvReturnValue=window.showModalDialog('http://www.google.cn/',[],'dialogWidth:200, dialogHeight:600, center=yes, resizable=yes, status=yes, edge=sunken, help=yes');\r\n");
      out.write("}\r\n");
      out.write("function register() {\r\n");
      out.write("\twindow.showModalDialog('register.jsp',[],'dialogWidth:200, dialogHeight:600, center=yes, resizable=yes, status=yes, edge=sunken, help=yes');\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/main.js\"></script>\r\n");
      out.write("<body topmargin=\"0\" rightmargin=\"0\" bottommargin=\"0\" leftmargin=\"0\" style=\"margin: 0px; padding: 0px;\">\r\n");
      out.write("\t<div style=\"width: 100%; height: 26px; background: linear-gradient(-90deg, #FCFCFC 0px, #F5F5F5 100%) repeat scroll 0 0 transparent; border-bottom: 1px solid #DCDCDC;\">\r\n");
      out.write("\t\t<div style=\"width: 990px; height: inherit; line-height: 26px; margin: 0px auto; border-bottom: 1px solid #DCDCDC;\">\r\n");
      out.write("\t\t\t<p style=\"float: left; height: 14px; line-height: 14px; padding: 6px 0; width: 300px;\">\r\n");
      out.write("\t\t\t\t<a style=\"display: block; font-size: 12px; height: 14px; line-height: 14px; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t<i style=\"font-size: 12px; line-height: 14px; display: block; float: left; height: 14px; margin-right: 4px; width: 14px; background-position: -578px -40px; background-image: url('https://i.alipayobjects.com/e/201305/PrarBa94X.png');\"></i>手机版\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<ul style=\"list-style: none outside none; color: #666666; float: right; padding: 6px 0; position: relative; z-index: 1000;\">\r\n");
      out.write("\t\t\t\t<li style=\"line-height: 12px;border: 1px solid transparent; padding: 1px 15px; font-size: 12px; float: left;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"recharge.jsp\">登录</a>\r\n");
      out.write("\t\t\t\t\t<b>-</b>\r\n");
      out.write("\t\t\t\t\t<a href=\"recharge.jsp\">注册</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menuitem-i\" style=\"line-height: 12px; padding: 1px 15px; border: 1px solid transparent; border-left: 1px solid #E2E2E2; border-right: 1px solid #E2E2E2; position: relative; float: left;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"i.do\" style=\"text-decoration: none; color: #666666;\">我的账户</a>\r\n");
      out.write("\t\t\t\t\t<i style=\"background-position: -592px -40px; display: inline-block; height: 12px; line-height: 10px; overflow: hidden; vertical-align: middle; width: 12px; background-image: url('https://i.alipayobjects.com/e/201305/PrarBa94X.png');\"></i>\r\n");
      out.write("\t\t\t\t\t<ul id=\"menuitem-i-sub\" style=\"background-color: #FFFFFF; list-style: none outside none; margin: 0; padding: 0; font-size: 12px; display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"recharge.jsp\">充值</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>交易记录</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"transfer.jsp\">转账</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><hr></hr></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"i.jsp\">我的账户</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li style=\"float: left; line-height: 12px; padding: 1px 15px; font-size: 12px;\"><a href=\"javascript: void(0);\" style=\"text-decoration: none; color: #666666;\">帮助中心</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("\t\t$(\"#menuitem-i\").mouseover(function() {\r\n");
      out.write("\t\t\t$(this).css(\"border\", \"1px solid #CCCCCC\");\r\n");
      out.write("\t\t\t$(this).css(\"border-bottom\", \"1px solid #E2E2E2\");\r\n");
      out.write("\t\t\t//$(this).css(\"background-color\", \"#FFFFFF\");\r\n");
      out.write("\t\t\t$(this).css(\"padding-top\", \"3px\");\r\n");
      out.write("\t\t\t//$(this).css(\"top\", \"-3px\");\r\n");
      out.write("\t\t\t$(\"#menuitem-i-sub\").css(\"display\", \"block\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#menuitem-i\").mouseout(function() {\r\n");
      out.write("\t\t\t$(this).css(\"border\", \"1px solid #E2E2E2\");\r\n");
      out.write("\t\t\t$(this).css(\"border-bottom\", \"0px solid transparent\");\r\n");
      out.write("\t\t\t$(this).css(\"border-top\", \"0px solid transparent\");\r\n");
      out.write("\t\t\t//$(this).css(\"background\", \"\");\r\n");
      out.write("\t\t\t$(this).css(\"padding-top\", \"3px\");\r\n");
      out.write("\t\t\t//$(this).css(\"top\", \"-3px\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#menuitem-i-sub\").css(\"display\", \"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<header style=\"height: 80px;  background-color: #FFFFFF; width: 100%; display: block; margin: 0; padding: 0;\">\r\n");
      out.write("\t\t<div style=\"height: 60px; width: 990px; padding-top: 18px; margin: 0px auto;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div style=\"background-color: #F9F9F9; border-bottom: 1px solid #FFFFFF; margin: 0 auto; min-width: 990px; overflow: hidden; position: relative; width: 100%; z-index: 100;\">\r\n");
      out.write("\t\t<ul style=\"width: 100%; height: 400px;\">\r\n");
      out.write("\t\t\t<li style=\"left: 0; opacity: 1; top: 0; z-index: 0; height: 400px;\">\r\n");
      out.write("\t\t\t\t<div style=\"background-position: 50% 50%; background-repeat: no-repeat; height: 100%; left: 0; opacity: 1; overflow: hidden; position: absolute; text-align: center; top: 0; transition: opacity 800ms ease-in-out 0s; vertical-align: middle; width: 100%; background-image: url('https://i.alipayobjects.com/e/201305/F4knLnqWL_src.jpg');\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width: 990px; height: 100%; margin: 0px auto; position: relative;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"header\" style=\"margin: 0px; padding: 0px; float: right; width: 100%\">\r\n");
      out.write("\t\t<div id=\"header2\" style=\"margin: 0px; padding: 0px; height: 60px\">\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='圈子Logo' title='音乐推荐，津津乐道: 只谈音乐' /><br/>\r\n");
      out.write("\t            <font style=\"font-size: x-small;\">我的</font>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='圈子Logo' title='音乐推荐，津津乐道: 只谈音乐' /><br/>\r\n");
      out.write("\t            <font style=\"font-size: x-small;\">系统消息</font>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='圈子Logo' title='音乐推荐，津津乐道: 只谈音乐' /><br/>\r\n");
      out.write("\t            <font style=\"font-size: x-small;\">系统设置</font>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' onclick='showLoginForm();' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='登录' title='登录' /><br/>\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' onclick='_show();' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='登录' title='登录' /><br/>\r\n");
      out.write("\t             -->\r\n");
      out.write("\t            <font style=\"font-size: x-small;\">登录</font>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<img src='images/IMG_0015.jpg' onclick='register();' width=\"40\" height=\"40\" \r\n");
      out.write("\t                alt='注册' title='注册'/><br/>\r\n");
      out.write("\t            <font style=\"font-size: x-small;\">注册</font>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<A href=\"javascript: calljojoo()\">点击测试</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<A href=\"javascript: login()\">登录</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<A href=\"javascript: calljojoo2()\">点击测试2</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<A href=\"javascript: register3()\">注册</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t\t\t<A href=\"javascript: calljojoo4()\">点击测试4</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"__center\" style=\"display: block; width: 100%; height: 400px; background-color: blue;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='login_form' align=\"center\" style=\"border-style: outset; display: none; width: 300px; height: 200px; background-color: window; position: absolute; top: 200px; left: 200px;\">\r\n");
      out.write("\t\t<div style=\"background-image: url('images/IMG_0015.jpg'); background-repeat: repeat; width: 100%; height: 50px;\"></div>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<div align=\"center\" style=\"width: 220px;\">\r\n");
      out.write("\t\t<form method=\"post\" action=\"CheckImageServlet\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t<label style=\"float:left; width:60px; color:#6E6E6E; font-size:12px;\" for=\"name\">帐户：<em></em></label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"rand\" maxlength=\"6\" value=\"\" style=\"width: 150px;\"/>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t如果用户不支持javascript ,默认显示的feedback,支持的话，在javascript中设置，每个规则都有对应的出错串\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<span class='feedback'></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t<label style=\"float:left; width:60px; color:#6E6E6E; font-size:12px;\" for=\"name\">密码：<em></em></label>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"rand\" maxlength=\"6\" value=\"\" style=\"width: 150px;\"/>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t如果用户不支持javascript ,默认显示的feedback,支持的话，在javascript中设置，每个规则都有对应的出错串\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<span class='feedback'></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p align=\"center\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"登录\"/>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t如果用户不支持javascript ,默认显示的feedback,支持的话，在javascript中设置，每个规则都有对应的出错串\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div style=\"background-repeat: repeat; width: 100%; height: 20px; text-align: right;\">忘记密码|<a  href=\"register.jsp\">注册新用户</a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section style=\"background-color: #F9F9F9; width: 100%; display: block; margin: 0; padding: 0;\">\r\n");
      out.write("\t\t<div style=\"width: 990px; margin: 0px auto;\">\r\n");
      out.write("\t\t\t<div style=\"background-color: #F9F9F9; border-bottom: 1px solid #E6E6E6; height: 160px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"background-color: #F9F9F9; border-top: 1px solid #FFFFFF; height: 58px; padding: 20px 0;\">\r\n");
      out.write("\t\t\t\t<article style=\"float: left; height: 55px; margin-right: 90px; position: relative; width: 270px;\">\r\n");
      out.write("\t\t\t\t\t<i style=\"display: block; height: 46px; left: 0; position: absolute; top: 3px; width: 46px; background: url('https://i.alipayobjects.com/e/201305/PrarBa94X.png') 0px 0px;\"></i>\r\n");
      out.write("\t\t\t\t\t<h3 style=\"background-position: -316px -30px; width: 155px; height: 30px; margin-bottom: 2px; margin-left: 60px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pay.jsp\" onclick=\"javascript: void(0);\" style=\"text-decoration: none;\">获取Ka卡</a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer style=\"background-color: #EDEDED; height: 280px; width: 100%; display: block; margin: 0; padding: 0;\">\r\n");
      out.write("\t\t<div style=\"background-repeat: repeat-x; height: 20px; width: 100%; background-repeat: repeat-x; height: 20px; width: 100%; background-image: url('https://i.alipayobjects.com/e/201303/2NwD1Q6ihZ.png');\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
